import type { LegalDoc } from "./types";

/**
 * Transcribed verbatim from documentation/legal/publicar/privacidad-es.md
 * (lawyer-reviewed text, plan-seo 4.5.4/4.5.5) — do not edit wording,
 * punctuation or order here. The only substitution made at build time is
 * the publication date placeholder, replaced by LEGAL_PUBLICATION_DATE
 * (see src/lib/legalDates.ts) in the page component, not in this file.
 */
export const privacidadEs: LegalDoc = {
  title: "Política de Privacidad",
  updatedLabel: "Última actualización",
  blocks: [
    { type: "h2", text: "1. Responsable del tratamiento" },
    { type: "p", text: "El responsable del tratamiento de los datos personales recopilados a través de basecoresales.com es Mariano Sandonato, persona física, CUIT 20-35996407-3, con domicilio en La Pampa 3000, 6.º C, CABA (C1428), Argentina. Para consultas relacionadas con privacidad y protección de datos puede contactarse a info@basecoresales.com." },
    { type: "h2", text: "2. Marco legal aplicable" },
    { type: "p", text: "Esta política se rige principalmente por la Ley 25.326 de Protección de los Datos Personales, su Decreto Reglamentario 1558/2001 y las disposiciones y resoluciones aplicables de la Agencia de Acceso a la Información Pública (AAIP)." },
    { type: "p", text: "La eventual aplicación del Reglamento (UE) 2016/679 (RGPD) se determina según sus propios criterios de ámbito territorial y no simplemente por el hecho de que el sitio esté disponible en inglés o pueda ser visitado desde Europa. Cuando el RGPD resulte aplicable a un tratamiento concreto, se aplicarán además las disposiciones correspondientes indicadas en la sección 8." },
    { type: "h2", text: "3. Datos que recopilamos y finalidades" },
    { type: "p", text: "Recopilamos los datos que la persona usuaria proporciona voluntariamente mediante los formularios del sitio, cuando solicita información, un diagnóstico, una reunión o la descarga de un recurso. No compramos bases de datos de terceros para estas finalidades." },
    { type: "h3", text: "3.1. Formulario de contacto" },
    { type: "p", text: "Datos: nombre, apellido (si se proporciona), empresa, servicio de interés, número de WhatsApp, correo electrónico (si se proporciona) y mensaje." },
    { type: "p", text: "Finalidades: responder la consulta, mantener el contacto solicitado, preparar una propuesta comercial cuando corresponda y coordinar una llamada o reunión solicitada por la persona." },
    { type: "p", text: "Base jurídica: consentimiento derivado del envío voluntario del formulario y, cuando exista una relación precontractual o contractual, el tratamiento de los datos necesarios para atenderla." },
    { type: "h3", text: "3.2. Formulario de descarga de e-book" },
    { type: "p", text: "Datos: nombre, apellido (si se proporciona), empresa, WhatsApp (si se proporciona) y correo electrónico." },
    { type: "p", text: "Finalidades: entregar el contenido solicitado y, cuando corresponda, atender la solicitud comercial iniciada por la persona. El envío de newsletters o comunicaciones comerciales recurrentes requiere consentimiento adicional mediante la casilla específica de marketing." },
    { type: "h3", text: "3.3. CRM — HubSpot" },
    { type: "p", text: "Los datos enviados mediante los formularios pueden almacenarse en nuestro CRM, actualmente HubSpot, para gestionar la consulta o solicitud concreta, registrar su origen y realizar el seguimiento comercial solicitado." },
    { type: "p", text: "Los datos pueden incluir nombre, apellido, empresa, correo electrónico, WhatsApp, servicio de interés, formulario de origen, mensaje y parámetros UTM presentes en la URL de origen. Los parámetros UTM se utilizan para identificar el origen de la conversión y no se utilizan por sí mismos para rastrear a la persona entre páginas." },
    { type: "p", text: "La incorporación al CRM no constituye por sí misma una autorización para enviar newsletters o comunicaciones comerciales recurrentes. Para ello se requiere el consentimiento separado descrito en el punto 3.4." },
    { type: "h3", text: "3.4. Comunicaciones comerciales y newsletter" },
    { type: "p", text: "Las comunicaciones comerciales recurrentes, novedades o newsletters se enviarán únicamente a quienes hayan marcado voluntariamente la casilla específica de marketing. La casilla no está premarcada y no es necesaria para enviar el formulario ni para recibir la respuesta o contenido solicitado." },
    { type: "p", text: "El consentimiento se registra junto con la fecha y, cuando corresponda, la información necesaria para acreditar cómo fue obtenido. Puede retirarse en cualquier momento, por ejemplo mediante el enlace de baja incluido en las comunicaciones o escribiendo a info@basecoresales.com." },
    { type: "h3", text: "3.5. Analítica — Google Analytics 4 y Cloudflare Web Analytics" },
    { type: "p", text: "Cuando la persona presta consentimiento mediante el banner de cookies, utilizamos Google Analytics 4 para obtener estadísticas sobre el uso del sitio, como páginas visitadas, origen aproximado del tráfico, dispositivo/navegador y eventos de interacción. Para ello Google Analytics utiliza identificadores técnicos (cookies) que permiten distinguir visitas y sesiones." },
    { type: "p", text: "La configuración evita el envío a Google Analytics de los datos personales introducidos en los formularios. La analítica se utiliza para medición y mejora del sitio y no para enviar newsletters. Si la persona no presta consentimiento, Google Analytics no se carga." },
    { type: "p", text: "Además, para conocer el volumen de visitas y el rendimiento técnico del sitio, utilizamos Cloudflare Web Analytics, que se carga en todas las páginas. Esta herramienta no instala cookies ni utiliza almacenamiento local en el dispositivo y no identifica ni sigue a la persona entre sesiones o entre sitios. Procesa datos técnicos de cada visita, como la página consultada, el sitio de procedencia, el tipo de navegador y dispositivo, el país aproximado y los tiempos de carga, y los presenta de forma agregada. No recibe los datos introducidos en los formularios. La base de este tratamiento es el interés legítimo en medir el funcionamiento del sitio de manera mínimamente invasiva." },
    { type: "h3", text: "3.6. WhatsApp" },
    { type: "p", text: "El sitio ofrece contacto mediante WhatsApp. Si la persona decide utilizar ese canal, o si nos proporciona su número en un formulario, podremos utilizarlo para responder a su solicitud y gestionar la conversación iniciada. El uso de WhatsApp implica además el tratamiento por parte de Meta/WhatsApp conforme a sus propias condiciones y políticas de privacidad." },
    { type: "h3", text: "3.7. Reserva de reuniones — HubSpot Meetings" },
    { type: "p", text: "Cuando la persona utiliza el sistema de reserva de reuniones de HubSpot, los datos que introduzca en dicho sistema se tratarán para gestionar la reserva, enviar comunicaciones relacionadas con la reunión y organizar la prestación solicitada. Este tratamiento se realiza además de los datos que eventualmente se hayan proporcionado previamente en el sitio." },
    { type: "h2", text: "4. Proveedores, encargados y transferencias internacionales" },
    { type: "p", text: "Para operar el sitio y prestar nuestros servicios utilizamos proveedores tecnológicos que pueden tratar datos por nuestra cuenta o recibir datos como parte del funcionamiento técnico. No vendemos datos personales a terceros para sus propios fines comerciales." },
    { type: "p", text: "Cuando un proveedor trata datos desde un país que no cuenta con un nivel adecuado reconocido por la normativa argentina, la transferencia internacional se apoya en un mecanismo válido conforme a la Ley 25.326, su decreto reglamentario y la normativa de la AAIP aplicable. Entre los mecanismos contractuales disponibles se encuentran los modelos aprobados por la Disposición 60/2016 y los modelos aprobados por la Resolución AAIP 198/2023. La existencia de cláusulas o mecanismos exigidos por otras jurisdicciones, como el RGPD, no se considera automáticamente suficiente para el análisis de la normativa argentina." },
    {
      type: "table",
      headers: ["Proveedor", "Función", "Datos / categoría", "Ubicación principal"],
      rows: [
        ["Resend", "Envío de los correos generados por los formularios del sitio", "Datos necesarios para el correo y contenido del formulario", "Estados Unidos"],
        ["HubSpot", "CRM, gestión de contactos y reserva de reuniones", "Datos identificativos, de contacto, empresa, solicitud y actividad asociada", "Unión Europea (Alemania)"],
        ["Google (Gmail)", "Recepción y gestión del correo de info@basecoresales.com", "Contenido de los correos recibidos y datos de contacto", "Estados Unidos"],
        ["Google (Analytics 4)", "Analítica del sitio, solo con consentimiento", "Datos de analítica, identificadores técnicos y eventos", "Estados Unidos"],
        ["Vercel", "Alojamiento y entrega técnica del sitio", "Datos técnicos necesarios para servir el sitio", "Estados Unidos"],
        ["Cloudflare", "Seguridad anti-bot (Turnstile), red de entrega, reenvío del correo de info@basecoresales.com y medición agregada de visitas y rendimiento (Web Analytics, sin cookies)", "Señales técnicas para prevenir envíos automatizados; correos en tránsito; datos técnicos de la visita", "Estados Unidos"],
      ],
    },
    { type: "p", text: "La lista se actualizará si se incorporan proveedores o tratamientos adicionales que impliquen datos personales." },
    { type: "h2", text: "5. Plazos de conservación" },
    { type: "ul", items: ["Consultas y contactos sin continuidad comercial: durante el tiempo necesario para atender la solicitud y, como regla general, hasta 12 meses desde el último contacto, salvo que exista una razón legítima para conservarlos durante un plazo diferente o que la persona solicite su supresión cuando corresponda.", "Clientes y relaciones contractuales: durante la vigencia de la relación y posteriormente durante los plazos necesarios para cumplir obligaciones legales y para el ejercicio o defensa de derechos, aplicando el plazo legal que corresponda al caso concreto.", "Documentación contable, fiscal y comprobantes: durante los plazos exigidos por la normativa fiscal y contable aplicable.", "Consentimientos de marketing: mientras sean necesarios para acreditar el consentimiento y gestionar la baja. Cuando una persona se opone a recibir comunicaciones, podremos conservar un registro mínimo de supresión/baja para evitar volver a contactarla por error.", "Cookies y tecnologías similares: según los plazos indicados en la Política de Cookies."] },
    { type: "p", text: "No se conservarán datos personales durante más tiempo del necesario para las finalidades informadas, salvo obligación legal o necesidad de ejercicio/defensa de derechos." },
    { type: "h2", text: "6. Derechos de las personas titulares" },
    { type: "ul", items: ["Acceso a los datos personales tratados y a la información prevista por la Ley 25.326.", "Rectificación y actualización de datos inexactos o desactualizados.", "Supresión cuando corresponda y no exista una obligación legal o causa legítima que impida eliminar los datos.", "Información sobre las finalidades y destinatarios del tratamiento.", "Retiro del consentimiento para tratamientos basados en consentimiento, sin afectar la licitud del tratamiento realizado antes de su retiro."] },
    { type: "p", text: "Para ejercer estos derechos, escribir a info@basecoresales.com indicando el derecho que se desea ejercer y proporcionando información razonable para acreditar la identidad. Los plazos aplicables serán los establecidos por la Ley 25.326 y su reglamentación." },
    { type: "h2", text: "7. Registro de bases de datos" },
    { type: "p", text: "Base Core cumplirá, cuando corresponda por la naturaleza y finalidad de sus bases de datos, con las obligaciones de inscripción ante el Registro Nacional de Bases de Datos Personales de la AAIP. La normativa argentina prevé la inscripción de las bases de datos personales alcanzadas por el régimen registral; la inscripción, modificación y baja de bases privadas se tramitan mediante TAD o GDE y son gratuitas. La determinación de la base registrable deberá efectuarse conforme al régimen vigente y a la estructura efectiva de los datos tratados." },
    { type: "h2", text: "8. RGPD / usuarios del Espacio Económico Europeo" },
    { type: "p", text: "El RGPD será aplicable únicamente cuando se cumplan sus criterios de ámbito territorial, por ejemplo, cuando exista una oferta de bienes o servicios dirigida a personas en el EEE o un seguimiento de su comportamiento dentro del ámbito previsto por el RGPD. La mera accesibilidad internacional del sitio no determina por sí sola su aplicación." },
    { type: "p", text: "Cuando el RGPD resulte aplicable, las personas podrán ejercer, según corresponda, los derechos de acceso, rectificación, supresión, limitación, oposición, portabilidad, retiro del consentimiento y los demás derechos reconocidos por el RGPD." },
    { type: "p", text: "Cuando corresponda, también podrán presentar una reclamación ante la autoridad de protección de datos competente de su lugar de residencia o ante la autoridad competente en España." },
    { type: "h2", text: "9. Seguridad" },
    { type: "p", text: "Aplicamos medidas técnicas y organizativas razonables destinadas a proteger los datos personales frente a acceso no autorizado, pérdida, alteración, destrucción o divulgación indebida. Entre ellas se incluyen el uso de conexiones HTTPS, controles de acceso a las herramientas utilizadas, gestión de credenciales y utilización de proveedores que mantienen medidas de seguridad propias." },
    { type: "p", text: "No se garantiza que ningún sistema conectado a Internet sea absolutamente invulnerable. En caso de un incidente relevante, se adoptarán las medidas de contención, investigación y comunicación que correspondan." },
    { type: "h2", text: "10. Menores" },
    { type: "p", text: "Los servicios de Base Core están dirigidos principalmente a empresas y profesionales. El sitio no está diseñado para recopilar deliberadamente datos de menores de edad. Si una persona considera que se han recopilado datos de un menor de manera indebida, puede comunicarse con info@basecoresales.com." },
    { type: "h2", text: "11. Cambios" },
    { type: "p", text: "Podemos actualizar esta política cuando cambien nuestras herramientas, tratamientos, servicios o requisitos legales. La fecha de actualización indicada al comienzo reflejará la versión vigente." },
  ],
};
