import type { BlogPost } from "../types";

export const howToCreateAMarketingStrategyForASmallBusiness: BlogPost = {
  title: "How to Create a Marketing Strategy for a Small Business",
  description:
    "Market analysis, positioning, target audience, channels, content, and metrics: what a real marketing strategy should include, and why it doesn't work in isolation from sales.",
  publishedAt: "2026-09-27",
  readingMinutes: 9,
  image: "/images/base-estadistica-base-core-sales-mkt-1.jpg",
  imageAlt: "Overhead view of an office desk with a laptop, printed charts, and a marketing metrics board",
  body: [
    {
      type: "p",
      text: "\"Marketing strategy\" is one of the most searched phrases online, and one of the most misunderstood. For many small businesses, it's shorthand for \"be active on social media\" or \"post content regularly.\" Neither of those is a strategy — they're tactics, and a tactic without a strategy behind it holds up for a few months, shows no clear results, and gets dropped before it ever had a real chance to work.",
    },
    {
      type: "h2",
      text: "What a marketing strategy is (and isn't)",
    },
    {
      type: "p",
      text: "A marketing strategy is the decision about who you're going to talk to, with what message, and through which channels, made before a single piece of content gets produced. A content calendar, a social media schedule, or an ad campaign are the execution of that decision, not the decision itself. The most common mistake small businesses make is jumping straight into execution (post, post, post) without answering the underlying questions first.",
    },
    {
      type: "h2",
      text: "Market analysis and positioning",
    },
    {
      type: "p",
      text: "Before deciding what to say, it helps to understand what's already being said: what direct competitors promise, what space is left open, and what the business has to offer that others aren't saying as clearly. Positioning isn't a catchy slogan — it's the concrete answer to \"why choose us instead of the option next door,\" and that answer needs to be backed by something real, not just a marketing phrase with nothing behind it.",
    },
    {
      type: "h2",
      text: "Target audience and value proposition",
    },
    {
      type: "p",
      text: "A well-defined target audience isn't \"small businesses with 10 to 50 employees\" — it's understanding the specific problem that business has, at what point in its growth that problem shows up, and who inside the company actually decides to solve it. The value proposition is the answer to that specific problem, stated in the customer's own terms, not in the internal jargon of whoever wrote it.",
    },
    {
      type: "h2",
      text: "Choosing channels: where your customer actually is, not where it's trendy to be",
    },
    {
      type: "p",
      text: "Every channel (social media, email, search, paid ads, events) carries a different production cost and a different kind of intent from the people consuming it. Picking a channel because \"everyone's there\" usually ends with content that the real target audience never actually sees. The question that cuts through this is simple: where is my customer actively searching for a solution to this problem, instead of just consuming entertainment?",
    },
    {
      type: "h2",
      text: "Content and lead capture",
    },
    {
      type: "p",
      text: "Content plays a different role depending on where someone is in their decision process: some content builds awareness (someone doesn't yet know they have the problem), and some content captures, meaning it turns an interested visitor into an identifiable lead. Mixing up those two roles is a common cause of \"we get a lot of reach but zero leads\": the content is entertaining, not capturing.",
    },
    {
      type: "h2",
      text: "Conversion: turning a visit into a lead",
    },
    {
      type: "p",
      text: "None of the above matters if whoever lands on the site or the profile has no clear path to leave their details or request information. A hidden form, a contact button buried three clicks deep, or a landing page without a single concrete reason to fill something out, are common ways to lose in conversion what was won in visibility.",
    },
    {
      type: "h2",
      text: "Metrics that matter (and the ones that don't)",
    },
    {
      type: "p",
      text: "**Reach, likes, and followers say little about whether the strategy is actually working.** The metrics that matter are the ones tied to the business itself:",
    },
    {
      type: "ul",
      items: [
        "Leads generated by channel, not just total traffic",
        "Cost per lead, to know whether the channel is sustainable over time",
        "Visit-to-lead conversion rate, not just impression-to-click",
        "How many of those leads actually move into a real sales conversation",
      ],
    },
    {
      type: "h2",
      text: "Common mistakes small businesses make here",
    },
    {
      type: "ul",
      items: [
        "Starting with content instead of positioning and target audience",
        "Copying a larger competitor's strategy without the budget or team to sustain it",
        "Measuring reach and engagement instead of leads and cost per lead",
        "Switching strategy every two or three months because \"it's not showing results,\" when the real issue is never finishing the execution of the previous one",
      ],
    },
    {
      type: "h2",
      text: "Why marketing without sales alignment never closes the loop",
    },
    {
      type: "p",
      text: "A marketing strategy can generate high-quality leads and still fail to turn into revenue if the sales team has no defined process for receiving, qualifying, and following up on them. Marketing and sales aren't two departments that happen to coexist — they're two halves of the same process. One generates demand, the other converts it, and neither performs at its best when the other operates on its own, without any real coordination between them.",
    },
  ],
  cta: {
    label: "SEE HOW WE RUN YOUR MARKETING",
    href: "/en/marketing",
  },
};
